# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.8'
services:
  productsservice:
    build:
      context: ./ProductsService
      dockerfile: Dockerfile
    ports:
      - "5000:5000"

  ordersservice:
    build:
      context: ./OrdersService
      dockerfile: Dockerfile
    ports:
      - "5001:5001"